apiVersion: v1
kind: Pod   
metadata:   
  name: configmap-demo   
spec:   
  containers:
    - name: test-container   
      image: ubuntu   
      command: [ "/bin/sh", "-c", "env" ]   
      env:   
        - name: SPECIAL_KEY   
          valueFrom:   
            configMapKeyRef:   
              name: special-config   
              key: special.how 
        - name: LOG_LEVEL  
          valueFrom:  
            configMapKeyRef:  
              name: env-config  
              key: log_level  
      resources:
        limits:
          cpu: 300m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
  restartPolicy: Never